/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package herobrine;

public class Herobrine {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) 
	{
    }
}
